### ISSUE TITLE
Send November newsletter

### ISSUE THREAD

**Issue by cbeams** [bitsquare/newsletter#5]
- [x] Phase Zero doc and slide deck
 - [x] Testnet genesis distribution
 - [x] Bisq at HCPP17 (Oct)
 - [x] WCN interview
 - [x] First compensation requsets and voting period (?)
 - [x] Invision prototypes
 - [x] Bisq at HB2017 in Riga (Nov)
 - [x] Bisq at 34C3 in Leipzig (Dec)
 - [x] bisq-contrib mailing list up / Google Group down
 - [x] next version on the way

**Comment by cbeams** [comment]
- [x] @ripcurlx, please reply here with updated invision prototype links and any text you want people to see about them.

**Comment by ripcurlx** [comment]
Hi @cbeams,

here we go:

> **Help us make Bisq even better!**
> We are continuing to improve Bisq now more than ever and need your support. Please click through following two prototypes showing our two main use cases (Sell & Buy Bitcoin using our current development build). As we know that some of you know the Bisq client for a long time, it would be great, if you could leave your comments within the prototype on things you don’t like, don’t understand or just would do differently. Also if you are completely new to Bisq, this is your chance to walk through the process of buying and selling Bitcoin with Bisq and give your unprejudiced comments.

> Bob wants to sell BTC (Create Offer) - https://invis.io/D6E67JWFH3
> Alice wants to buy BTC (Take Offer) - https://invis.io/46E67NTQR2

Thanks for your support!

**Comment by ripcurlx** [comment]
@cbeams Ah my bad - I thought this is the mail to the contributor. I just changed the content to fit for everyone else on the newsletter.

**Comment by cbeams** [comment]
I'll be writing the newsletter over the next couple hours. If anyone wants to see anything else get included, let me know.

**Comment by cbeams** [comment]
A draft of the November newsletter is at https://docs.google.com/document/d/115OzLRtdNnDpqhS2YhHHkGrWKBeefDhYX-hq-K3LrPs/edit

I'd like to send this out this afternoon European time (4-5 hours from the time of this comment). @ManfredKarrer, @ripcurlx, @sqrrm, @mrosseel, and anyone else who cares to, please have a look through it and provide any comments in the doc or in the #newsletter channel in Slack, thanks!

**Comment by cbeams** [comment]
Closing as complete. From http://mailchi.mp/b0de1efc7168/nov-2017-bisq-newsletter:

![screencapture-mailchi-mp-b0de1efc7168-nov-2017-bisq-newsletter-1510589461991](https://user-images.githubusercontent.com/301810/32735767-e8e87db4-c895-11e7-9ccb-af5b717225b2.png)
